modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/cassiancc/Creeper-Confetti-Plus/issues"
license = "MIT"

[[mods]]
modId = "creeperconfetti"
version = "${version}"
displayName = "Creeper Confetti Plus"
authors = "cassiancc"
description = '''
A mod that replaces the Creeper explosion with nice confetti - a port of Creeper Confetti to Architectury.
'''
logoFile = "assets/creeperconfetti/icon.png"

[[dependencies.creeperconfetti]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.creeperconfetti]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "creeperconfetti.mixins.json"
